begin;

create schema if not exists private;
revoke all on schema private from public;

do $$
begin
  create type public.app_role as enum ('admin', 'avaliador', 'empreendedor');
exception
  when duplicate_object then null;
end
$$;

do $$
begin
  create type public.submission_status as enum ('rascunho', 'enviada');
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.profiles (
  id text primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  email text not null unique check (email = lower(email)),
  role public.app_role not null default 'empreendedor',
  organization text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.startups (
  id text primary key,
  name text not null,
  founder text not null,
  sector text not null default '',
  city text not null default '',
  state text not null default '' check (char_length(state) <= 2),
  stage text not null default 'MVP',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profile_startups (
  profile_id text not null references public.profiles(id) on delete cascade,
  startup_id text not null references public.startups(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, startup_id)
);

create table if not exists public.journeys (
  id text primary key,
  position smallint not null unique check (position > 0),
  name text not null,
  description text not null,
  gate text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  journey_id text not null references public.journeys(id) on delete cascade,
  position smallint not null check (position > 0),
  prompt text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (journey_id, position)
);

create table if not exists public.assessment_periods (
  id bigint generated by default as identity primary key,
  month smallint not null check (month between 1 and 12),
  year smallint not null check (year between 2020 and 2100),
  label text not null,
  created_at timestamptz not null default now(),
  unique (year, month)
);

create table if not exists public.assessment_cycles (
  id bigint generated by default as identity primary key,
  startup_id text not null references public.startups(id) on delete cascade,
  period_id bigint not null references public.assessment_periods(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (startup_id, period_id)
);

create table if not exists public.entrepreneur_answers (
  cycle_id bigint not null references public.assessment_cycles(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  score numeric(2,1) not null check (score between 0 and 5),
  comment text not null default '',
  status public.submission_status not null default 'rascunho',
  updated_by text references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (cycle_id, question_id)
);

create table if not exists public.evaluator_answers (
  cycle_id bigint not null references public.assessment_cycles(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  score numeric(2,1) not null check (score between 0 and 5),
  comment text not null default '',
  status public.submission_status not null default 'rascunho',
  updated_by text references public.profiles(id) on delete set null,
  updated_at timestamptz not null default now(),
  primary key (cycle_id, question_id)
);

create index if not exists profiles_auth_user_idx
  on public.profiles(auth_user_id);
create index if not exists profile_startups_startup_idx
  on public.profile_startups(startup_id);
create index if not exists questions_journey_idx
  on public.questions(journey_id, position);
create index if not exists assessment_cycles_startup_idx
  on public.assessment_cycles(startup_id);
create index if not exists assessment_cycles_period_idx
  on public.assessment_cycles(period_id);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function private.set_updated_at();

drop trigger if exists startups_set_updated_at on public.startups;
create trigger startups_set_updated_at
before update on public.startups
for each row execute function private.set_updated_at();

drop trigger if exists journeys_set_updated_at on public.journeys;
create trigger journeys_set_updated_at
before update on public.journeys
for each row execute function private.set_updated_at();

drop trigger if exists questions_set_updated_at on public.questions;
create trigger questions_set_updated_at
before update on public.questions
for each row execute function private.set_updated_at();

drop trigger if exists assessment_cycles_set_updated_at on public.assessment_cycles;
create trigger assessment_cycles_set_updated_at
before update on public.assessment_cycles
for each row execute function private.set_updated_at();

create or replace function private.current_profile_id()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select p.id
  from public.profiles p
  where p.auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function private.current_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select p.role
  from public.profiles p
  where p.auth_user_id = (select auth.uid())
  limit 1
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.current_role() = 'admin'::public.app_role, false)
$$;

create or replace function private.can_access_startup(target_startup_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    private.is_admin()
    or exists (
      select 1
      from public.profile_startups ps
      where ps.profile_id = private.current_profile_id()
        and ps.startup_id = target_startup_id
    )
$$;

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_email text := lower(coalesce(new.email, ''));
  display_name text := coalesce(
    nullif(new.raw_user_meta_data ->> 'name', ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    split_part(normalized_email, '@', 1)
  );
begin
  update public.profiles
  set auth_user_id = new.id,
      name = case when name = '' then display_name else name end
  where email = normalized_email;

  if not found then
    insert into public.profiles (id, auth_user_id, name, email, role, organization)
    values (
      new.id::text,
      new.id,
      display_name,
      normalized_email,
      'empreendedor',
      ''
    );
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_auth_user();

revoke all on function private.current_profile_id() from public;
revoke all on function private.current_role() from public;
revoke all on function private.is_admin() from public;
revoke all on function private.can_access_startup(text) from public;
grant usage on schema private to authenticated;
grant execute on function private.current_profile_id() to authenticated;
grant execute on function private.current_role() to authenticated;
grant execute on function private.is_admin() to authenticated;
grant execute on function private.can_access_startup(text) to authenticated;

alter table public.profiles enable row level security;
alter table public.startups enable row level security;
alter table public.profile_startups enable row level security;
alter table public.journeys enable row level security;
alter table public.questions enable row level security;
alter table public.assessment_periods enable row level security;
alter table public.assessment_cycles enable row level security;
alter table public.entrepreneur_answers enable row level security;
alter table public.evaluator_answers enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select
on public.profiles for select
to authenticated
using (
  id = private.current_profile_id()
  or private.is_admin()
);

drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin
on public.profiles for update
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists startups_select_accessible on public.startups;
create policy startups_select_accessible
on public.startups for select
to authenticated
using (private.can_access_startup(id));

drop policy if exists startups_manage_admin on public.startups;
create policy startups_manage_admin
on public.startups for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists profile_startups_select on public.profile_startups;
create policy profile_startups_select
on public.profile_startups for select
to authenticated
using (
  profile_id = private.current_profile_id()
  or private.is_admin()
);

drop policy if exists profile_startups_manage_admin on public.profile_startups;
create policy profile_startups_manage_admin
on public.profile_startups for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists journeys_select_authenticated on public.journeys;
create policy journeys_select_authenticated
on public.journeys for select
to authenticated
using (true);

drop policy if exists journeys_manage_admin on public.journeys;
create policy journeys_manage_admin
on public.journeys for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists questions_select_authenticated on public.questions;
create policy questions_select_authenticated
on public.questions for select
to authenticated
using (true);

drop policy if exists questions_manage_admin on public.questions;
create policy questions_manage_admin
on public.questions for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists periods_select_authenticated on public.assessment_periods;
create policy periods_select_authenticated
on public.assessment_periods for select
to authenticated
using (true);

drop policy if exists periods_manage_admin on public.assessment_periods;
create policy periods_manage_admin
on public.assessment_periods for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists cycles_select_accessible on public.assessment_cycles;
create policy cycles_select_accessible
on public.assessment_cycles for select
to authenticated
using (private.can_access_startup(startup_id));

drop policy if exists cycles_manage_admin on public.assessment_cycles;
create policy cycles_manage_admin
on public.assessment_cycles for all
to authenticated
using (private.is_admin())
with check (private.is_admin());

drop policy if exists entrepreneur_answers_select on public.entrepreneur_answers;
create policy entrepreneur_answers_select
on public.entrepreneur_answers for select
to authenticated
using (
  exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists entrepreneur_answers_insert on public.entrepreneur_answers;
create policy entrepreneur_answers_insert
on public.entrepreneur_answers for insert
to authenticated
with check (
  private.current_role() = 'empreendedor'
  and updated_by = private.current_profile_id()
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists entrepreneur_answers_update on public.entrepreneur_answers;
create policy entrepreneur_answers_update
on public.entrepreneur_answers for update
to authenticated
using (
  private.current_role() = 'empreendedor'
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
)
with check (
  private.current_role() = 'empreendedor'
  and updated_by = private.current_profile_id()
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists entrepreneur_answers_delete on public.entrepreneur_answers;
create policy entrepreneur_answers_delete
on public.entrepreneur_answers for delete
to authenticated
using (
  private.is_admin()
  or (
    private.current_role() = 'empreendedor'
    and exists (
      select 1
      from public.assessment_cycles c
      where c.id = cycle_id
        and private.can_access_startup(c.startup_id)
    )
  )
);

drop policy if exists evaluator_answers_select on public.evaluator_answers;
create policy evaluator_answers_select
on public.evaluator_answers for select
to authenticated
using (
  exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists evaluator_answers_insert on public.evaluator_answers;
create policy evaluator_answers_insert
on public.evaluator_answers for insert
to authenticated
with check (
  private.current_role() = 'avaliador'
  and updated_by = private.current_profile_id()
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists evaluator_answers_update on public.evaluator_answers;
create policy evaluator_answers_update
on public.evaluator_answers for update
to authenticated
using (
  private.current_role() = 'avaliador'
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
)
with check (
  private.current_role() = 'avaliador'
  and updated_by = private.current_profile_id()
  and exists (
    select 1
    from public.assessment_cycles c
    where c.id = cycle_id
      and private.can_access_startup(c.startup_id)
  )
);

drop policy if exists evaluator_answers_delete on public.evaluator_answers;
create policy evaluator_answers_delete
on public.evaluator_answers for delete
to authenticated
using (
  private.is_admin()
  or (
    private.current_role() = 'avaliador'
    and exists (
      select 1
      from public.assessment_cycles c
      where c.id = cycle_id
        and private.can_access_startup(c.startup_id)
    )
  )
);

grant usage on schema public to authenticated;
revoke all on public.profiles from anon;
revoke all on public.startups from anon;
revoke all on public.profile_startups from anon;
revoke all on public.journeys from anon;
revoke all on public.questions from anon;
revoke all on public.assessment_periods from anon;
revoke all on public.assessment_cycles from anon;
revoke all on public.entrepreneur_answers from anon;
revoke all on public.evaluator_answers from anon;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.startups to authenticated;
grant select, insert, update, delete on public.profile_startups to authenticated;
grant select, insert, update, delete on public.journeys to authenticated;
grant select, insert, update, delete on public.questions to authenticated;
grant select, insert, update, delete on public.assessment_periods to authenticated;
grant select, insert, update, delete on public.assessment_cycles to authenticated;
grant select, insert, update, delete on public.entrepreneur_answers to authenticated;
grant select, insert, update, delete on public.evaluator_answers to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.startups
  (id, name, founder, sector, city, state, stage, description)
values
  (
    'agrosense',
    'Startup Alpha',
    'Pessoa Demo Alpha',
    'Agtech',
    'Sao Paulo',
    'SP',
    'MVP',
    'Exemplo ficticio de sensoriamento e inteligencia preditiva para produtores.'
  ),
  (
    'healthflow',
    'Startup Beta',
    'Pessoa Demo Beta',
    'Healthtech',
    'Recife',
    'PE',
    'Piloto',
    'Exemplo ficticio de orquestracao de jornada assistencial.'
  ),
  (
    'educamatch',
    'Startup Gamma',
    'Pessoa Demo Gamma',
    'Edtech',
    'Florianopolis',
    'SC',
    'Tração',
    'Exemplo ficticio de matching de trilhas personalizadas.'
  )
on conflict (id) do update set
  name = excluded.name,
  founder = excluded.founder,
  sector = excluded.sector,
  city = excluded.city,
  state = excluded.state,
  stage = excluded.stage,
  description = excluded.description;

insert into public.profiles
  (id, name, email, role, organization)
values
  ('admin-demo', 'Admin Demo', 'admin@example.com', 'admin', 'Organizacao Demo'),
  ('avaliador-demo-1', 'Avaliador Demo 1', 'avaliador1@example.com', 'avaliador', 'Consultoria Demo'),
  ('avaliador-demo-2', 'Avaliador Demo 2', 'avaliador2@example.com', 'avaliador', 'Mentoria Demo'),
  ('empreendedor-demo', 'Empreendedor Demo', 'empreendedor@example.com', 'empreendedor', 'Startup Alpha')
on conflict (id) do update set
  name = excluded.name,
  email = excluded.email,
  role = excluded.role,
  organization = excluded.organization;

insert into public.profile_startups (profile_id, startup_id)
values
  ('admin-demo', 'agrosense'),
  ('admin-demo', 'healthflow'),
  ('admin-demo', 'educamatch'),
  ('avaliador-demo-1', 'agrosense'),
  ('avaliador-demo-1', 'healthflow'),
  ('avaliador-demo-2', 'educamatch'),
  ('empreendedor-demo', 'agrosense')
on conflict do nothing;

insert into public.journeys
  (id, position, name, description, gate)
values
  (
    'conceito',
    1,
    'Conceito',
    'Comprovar que existe uma dor relevante, recorrente e suficientemente grande.',
    'Vale a pena resolver?'
  ),
  (
    'produto',
    2,
    'Produto',
    'Comprovar que a solução entrega valor real aos usuários.',
    'Conseguimos resolver?'
  ),
  (
    'negocios',
    3,
    'Negócios',
    'Comprovar que a solução pode gerar sustentabilidade econômica.',
    'Conseguimos sustentar?'
  ),
  (
    'crescimento',
    4,
    'Crescimento',
    'Comprovar que o modelo consegue escalar com eficiência, qualidade e propósito.',
    'Conseguimos escalar?'
  )
on conflict (id) do update set
  position = excluded.position,
  name = excluded.name,
  description = excluded.description,
  gate = excluded.gate;

with question_seed(journey_id, prompts) as (
  values
    (
      'conceito',
      array[
        'O problema está claramente definido?',
        'O problema realmente existe com evidências?',
        'O público afetado está bem identificado?',
        'A dor é frequente ou recorrente?',
        'O impacto do problema é relevante?',
        'As soluções atuais foram mapeadas?',
        'Existe uma oportunidade clara de mercado?',
        'O nicho inicial está definido?',
        'Existem dados ou pesquisas que sustentam a oportunidade?',
        'A dor justifica a criação de uma solução?'
      ]::text[]
    ),
    (
      'produto',
      array[
        'A solução está claramente descrita?',
        'A proposta de valor é fácil de entender?',
        'As funcionalidades essenciais estão definidas?',
        'Existe protótipo, MVP ou versão testável?',
        'Usuários já testaram a solução?',
        'Os usuários percebem valor na solução?',
        'A solução é simples de usar?',
        'Existe diferenciação frente às alternativas atuais?',
        'A solução é tecnicamente viável?',
        'Existem evidências de que o produto resolve o problema?'
      ]::text[]
    ),
    (
      'negocios',
      array[
        'Está claro quem paga pela solução?',
        'Existe disposição de pagamento validada?',
        'O modelo de receita está definido?',
        'O mercado endereçável está estimado?',
        'O segmento inicial de clientes está priorizado?',
        'Existem canais de aquisição definidos?',
        'O processo comercial está minimamente estruturado?',
        'Os custos principais da operação são conhecidos?',
        'A margem esperada é sustentável?',
        'Existe caminho claro para atingir ponto de equilíbrio?'
      ]::text[]
    ),
    (
      'crescimento',
      array[
        'A operação suporta aumento de clientes?',
        'Os principais gargalos de escala foram identificados?',
        'Existem canais de crescimento testados?',
        'Há estratégia para aumentar retenção?',
        'Há estratégia para aumentar ticket médio?',
        'Existem oportunidades de expansão de mercado?',
        'A startup sabe se precisará captar recursos?',
        'Existem indicadores de gestão acompanhados?',
        'A governança mínima está estruturada?',
        'O crescimento mantém qualidade, eficiência e propósito?'
      ]::text[]
    )
)
insert into public.questions (journey_id, position, prompt)
select
  qs.journey_id,
  item.ordinality::smallint,
  item.prompt
from question_seed qs
cross join lateral unnest(qs.prompts) with ordinality as item(prompt, ordinality)
on conflict (journey_id, position) do update set
  prompt = excluded.prompt,
  active = true;

insert into public.assessment_periods (month, year, label)
values
  (2, 2026, 'Fev/2026'),
  (3, 2026, 'Mar/2026'),
  (4, 2026, 'Abr/2026'),
  (5, 2026, 'Mai/2026')
on conflict (year, month) do update set label = excluded.label;

insert into public.assessment_cycles (startup_id, period_id)
select s.id, p.id
from public.startups s
cross join public.assessment_periods p
where s.id in ('agrosense', 'healthflow', 'educamatch')
  and p.year = 2026
  and p.month between 2 and 5
on conflict (startup_id, period_id) do nothing;

create temporary table seed_targets (
  startup_id text not null,
  month smallint not null,
  journey_id text not null,
  target numeric(2,1) not null
) on commit drop;

insert into seed_targets (startup_id, month, journey_id, target)
values
  ('agrosense', 2, 'conceito', 3.8),
  ('agrosense', 2, 'produto', 2.3),
  ('agrosense', 2, 'negocios', 1.8),
  ('agrosense', 2, 'crescimento', 1.2),
  ('agrosense', 3, 'conceito', 4.0),
  ('agrosense', 3, 'produto', 2.7),
  ('agrosense', 3, 'negocios', 2.0),
  ('agrosense', 3, 'crescimento', 1.5),
  ('agrosense', 4, 'conceito', 4.2),
  ('agrosense', 4, 'produto', 3.1),
  ('agrosense', 4, 'negocios', 2.2),
  ('agrosense', 4, 'crescimento', 1.8),
  ('agrosense', 5, 'conceito', 4.4),
  ('agrosense', 5, 'produto', 3.4),
  ('agrosense', 5, 'negocios', 2.4),
  ('agrosense', 5, 'crescimento', 2.1),
  ('healthflow', 2, 'conceito', 3.1),
  ('healthflow', 2, 'produto', 3.7),
  ('healthflow', 2, 'negocios', 2.5),
  ('healthflow', 2, 'crescimento', 2.1),
  ('healthflow', 3, 'conceito', 3.2),
  ('healthflow', 3, 'produto', 3.9),
  ('healthflow', 3, 'negocios', 2.7),
  ('healthflow', 3, 'crescimento', 2.3),
  ('healthflow', 4, 'conceito', 3.4),
  ('healthflow', 4, 'produto', 4.1),
  ('healthflow', 4, 'negocios', 2.9),
  ('healthflow', 4, 'crescimento', 2.5),
  ('healthflow', 5, 'conceito', 3.5),
  ('healthflow', 5, 'produto', 4.3),
  ('healthflow', 5, 'negocios', 3.0),
  ('healthflow', 5, 'crescimento', 2.7),
  ('educamatch', 2, 'conceito', 2.7),
  ('educamatch', 2, 'produto', 2.5),
  ('educamatch', 2, 'negocios', 2.1),
  ('educamatch', 2, 'crescimento', 1.1),
  ('educamatch', 3, 'conceito', 3.0),
  ('educamatch', 3, 'produto', 2.9),
  ('educamatch', 3, 'negocios', 2.5),
  ('educamatch', 3, 'crescimento', 1.4),
  ('educamatch', 4, 'conceito', 3.4),
  ('educamatch', 4, 'produto', 3.2),
  ('educamatch', 4, 'negocios', 2.8),
  ('educamatch', 4, 'crescimento', 1.8),
  ('educamatch', 5, 'conceito', 3.8),
  ('educamatch', 5, 'produto', 3.6),
  ('educamatch', 5, 'negocios', 3.1),
  ('educamatch', 5, 'crescimento', 2.2);

insert into public.entrepreneur_answers
  (cycle_id, question_id, score, comment, status)
select
  c.id,
  q.id,
  greatest(
    0,
    least(
      5,
      round(
        t.target
        + ((((q.position - 1) % 5) - 2) * 0.16)
        + case
            when t.startup_id = 'healthflow' then 0.82
            when t.startup_id = 'agrosense' then 0.32
            else 0.18
          end,
        1
      )
    )
  ),
  '',
  'enviada'
from seed_targets t
join public.assessment_periods p
  on p.year = 2026 and p.month = t.month
join public.assessment_cycles c
  on c.startup_id = t.startup_id and c.period_id = p.id
join public.questions q
  on q.journey_id = t.journey_id
on conflict (cycle_id, question_id) do nothing;

insert into public.evaluator_answers
  (cycle_id, question_id, score, comment, status)
select
  c.id,
  q.id,
  greatest(
    0,
    least(
      5,
      round(
        t.target
        - ((((q.position - 1) % 5) - 2) * 0.16)
        + case when t.startup_id = 'healthflow' then -0.42 else -0.08 end,
        1
      )
    )
  ),
  case
    when t.target < 3
      then 'Necessário transformar hipótese em evidência mensurável.'
    else 'Boa base, com oportunidade de documentar aprendizados.'
  end,
  'enviada'
from seed_targets t
join public.assessment_periods p
  on p.year = 2026 and p.month = t.month
join public.assessment_cycles c
  on c.startup_id = t.startup_id and c.period_id = p.id
join public.questions q
  on q.journey_id = t.journey_id
on conflict (cycle_id, question_id) do nothing;

create or replace view public.assessment_question_results
with (security_invoker = true)
as
select
  c.id as cycle_id,
  c.startup_id,
  p.id as period_id,
  p.month,
  p.year,
  p.label,
  j.id as journey_id,
  j.position as journey_position,
  j.name as journey_name,
  j.gate,
  q.id as question_id,
  q.position as question_position,
  q.prompt,
  ea.score as entrepreneur_score,
  ea.comment as entrepreneur_comment,
  ea.status as entrepreneur_status,
  ea.updated_at as entrepreneur_updated_at,
  va.score as evaluator_score,
  va.comment as evaluator_comment,
  va.status as evaluator_status,
  va.updated_at as evaluator_updated_at,
  case
    when ea.score is not null and va.score is not null
      then round((ea.score * 0.4) + (va.score * 0.6), 2)
    else null
  end as final_score,
  case
    when ea.score is not null and va.score is not null
      then round(ea.score - va.score, 2)
    else null
  end as gap
from public.assessment_cycles c
join public.assessment_periods p on p.id = c.period_id
join public.questions q on q.active
join public.journeys j on j.id = q.journey_id
left join public.entrepreneur_answers ea
  on ea.cycle_id = c.id and ea.question_id = q.id
left join public.evaluator_answers va
  on va.cycle_id = c.id and va.question_id = q.id;

revoke all on public.assessment_question_results from anon;
grant select on public.assessment_question_results to authenticated;

commit;
